import {
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowRight,
  LucideArrowUp,
  LucideBell,
  LucideBookmark,
  LucideBraces,
  LucideCalendar,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCircleHelp,
  LucideClock,
  LucideCode,
  LucideComponent,
  LucideDisc,
  LucideDownload,
  LucideExternalLink,
  LucideEye,
  LucideEyeOff,
  LucideFastForward,
  LucideGitBranch,
  LucideHeart,
  LucideHome,
  LucideInfo,
  LucideLayers,
  LucideListMusic,
  LucideLock,
  LucideMail,
  LucideMenu,
  LucideMinus,
  LucideMusic,
  LucidePackage,
  LucidePalette,
  LucidePause,
  LucidePencil,
  LucidePlay,
  LucidePlus,
  LucideRepeat,
  LucideRewind,
  LucideSearch,
  LucideSettings,
  LucideSettings2,
  LucideShuffle,
  LucideSkipBack,
  LucideSkipForward,
  LucideSquare,
  LucideStar,
  LucideTerminal,
  LucideTrash,
  LucideTriangleAlert,
  LucideUnlock,
  LucideUpload,
  LucideUser,
  LucideUsers,
  LucideVolume,
  LucideVolume1,
  LucideVolume2,
  LucideVolumeX,
  LucideX,
  type LucideIcon,
} from '@lucide/angular';

export const NC_ICONS = {
  play: LucidePlay,
  pause: LucidePause,
  stop: LucideSquare,
  'skip-back': LucideSkipBack,
  'skip-forward': LucideSkipForward,
  rewind: LucideRewind,
  'fast-forward': LucideFastForward,
  volume: LucideVolume,
  'volume-1': LucideVolume1,
  'volume-2': LucideVolume2,
  'volume-x': LucideVolumeX,
  'volume-muted': LucideVolumeX,
  repeat: LucideRepeat,
  shuffle: LucideShuffle,
  music: LucideMusic,
  disc: LucideDisc,
  'list-music': LucideListMusic,
  'arrow-left': LucideArrowLeft,
  'arrow-right': LucideArrowRight,
  'arrow-up': LucideArrowUp,
  'arrow-down': LucideArrowDown,
  'chevron-left': LucideChevronLeft,
  'chevron-right': LucideChevronRight,
  'chevron-up': LucideChevronUp,
  'chevron-down': LucideChevronDown,
  menu: LucideMenu,
  x: LucideX,
  plus: LucidePlus,
  minus: LucideMinus,
  search: LucideSearch,
  settings: LucideSettings,
  edit: LucidePencil,
  trash: LucideTrash,
  download: LucideDownload,
  upload: LucideUpload,
  'external-link': LucideExternalLink,
  check: LucideCheck,
  'check-circle': LucideCircleCheck,
  info: LucideInfo,
  'alert-circle': LucideCircleAlert,
  'alert-triangle': LucideTriangleAlert,
  'help-circle': LucideCircleHelp,
  home: LucideHome,
  user: LucideUser,
  users: LucideUsers,
  calendar: LucideCalendar,
  clock: LucideClock,
  heart: LucideHeart,
  star: LucideStar,
  bookmark: LucideBookmark,
  mail: LucideMail,
  bell: LucideBell,
  lock: LucideLock,
  unlock: LucideUnlock,
  eye: LucideEye,
  'eye-off': LucideEyeOff,
  code: LucideCode,
  terminal: LucideTerminal,
  package: LucidePackage,
  layers: LucideLayers,
  component: LucideComponent,
  palette: LucidePalette,
  'settings-2': LucideSettings2,
  braces: LucideBraces,
  'git-branch': LucideGitBranch,
} as const satisfies Record<string, LucideIcon>;

export type NcIconName = keyof typeof NC_ICONS;

export const NC_ICON_NAMES = Object.keys(NC_ICONS) as NcIconName[];

export function isNcIconName(name: string): name is NcIconName {
  return Object.hasOwn(NC_ICONS, name);
}

export function getNcIcon(name: string): LucideIcon | null {
  return isNcIconName(name) ? NC_ICONS[name] : null;
}
